### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by smithbill17** [hvalev/bh1750mqtt-homeassistant-docker#12]
I have a Raspberry Pi2b onto which I've installed the latest Home Assistant OS 8.1 & Core 2022.5.5 (ie. the latest HA crippled with the deprecated GPIO support). Attached to the GPIO pins on the rpi2b is a BH1750.

I've installed the Portainer AddOn and added a new Container as per the details given in your installation instructions.

I can then start the new Container which immediately stops with the below errors in logs for the Container:

```
Traceback (most recent call last):
  File "//bh1750mqtt.py", line 105, in <module>
    raise error
  File "//bh1750mqtt.py", line 97, in <module>
    bus = smbus.SMBus(bh1750_bus)  # Rev 2 Pi uses 1
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "//bh1750mqtt.py", line 105, in <module>
    raise error
  File "//bh1750mqtt.py", line 97, in <module>
    bus = smbus.SMBus(bh1750_bus)  # Rev 2 Pi uses 1
FileNotFoundError: [Errno 2] No such file or directory

```
Admittedly, I don't entirely know what I'm doing. I simply wanted to get LUX values from my connected BH1750 into HomeAssistant (I believe I have to do it via MQTT now). I know my BH1750 works correctly, because it was working perfectly before they decided to deprecate support for GPIO in the latest HomeAssistant.

**Comment by hvalev** [comment]
That's an interesting error. Did you run the container from portainer including the variables provided in the docker-compose or docker run commands? Did you also use the prebuilt docker image from docker hub?

**Comment by smithbill17** [comment]
I think the answer to both questions is yes - I've attached a couple of images. I entered the docker run command into the 'Command - Override' box exactly as you have it in the instructions but with my MQTT broker IP address.

However, I'm going to admit that a) i've no real idea what I'm doing b) i've managed to get my BH1750 sensor working using a Custom Integration instead, so probably won't pursue using a docker image with MQTT. I guess you can either close this issue or investigate if I've managed to provide you with enough details already.
![Screenshot_2022-05-28-18-15-37-175_com android chrome](https://user-images.githubusercontent.com/66825587/170836319-f2efabc4-d484-4260-9cd4-e3cf24e3afa0.jpg)
![Screenshot_2022-05-28-18-14-08-334_com android chrome](https://user-images.githubusercontent.com/66825587/170836321-a121ed7f-c13a-4a73-ad0b-6d7951904681.jpg)

**Comment by hvalev** [comment]
So I have two quick suggestions that you can try. The first is to try a different bus version. Luckily, I have exposed this variable to be modifiable from outside of the container using an environmental variable. You can do that by appending `-e bus=0` to your docker command. The alternative is to also check which data pin you use for your bh1750 sensor. The tool to do that is called i2scanner, but it doesn't work on older raspberry pi models. However, there is this github repository https://github.com/ionjet/i2csan which can help you identify the pin. Then you can set this pin by using another environmental variable in the docker run command and namely `-e addr=....`. The number you will enter is a hexadecimal. If you check the repository's readme, you can figure out how it is created. Let me know how it goes.

Ah, I've just read your reply more carefully and found that you went with a different solution. No worries, I'll leave my reply here for posterity.
